apiVersion: apps/v1
kind: Deployment
metadata:
  name: note4u-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: note4u
  template:
    metadata:
      labels:
        app: note4u
    spec:
      containers:
      - name: note4u
        image: 580644016044.dkr.ecr.ap-northeast-2.amazonaws.com/note4u:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: note4u-secret
